# Generated by Django 4.1.4 on 2023-05-19 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='BuySellMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=50)),
                ('operation', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('day', models.CharField(max_length=50)),
                ('quantity', models.CharField(max_length=50)),
                ('total_movement', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DepositExtractionMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=50)),
                ('operation', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('day', models.CharField(max_length=50)),
                ('quantity', models.CharField(max_length=50)),
                ('total_movement', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=50)),
                ('variation', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('quantity', models.CharField(max_length=50)),
                ('amount', models.CharField(max_length=50)),
            ],
        ),
    ]
