# Generated by Django 4.1.4 on 2023-06-07 19:53

import api_v1.Encrypt
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CocosCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('company_id', models.IntegerField(default=None)),
                ('username', models.CharField(max_length=255)),
                ('password', api_v1.Encrypt.EncryptedPasswordField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EncryptedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cocos_password', api_v1.Encrypt.EncryptedPasswordField(blank=True, max_length=100, null=True)),
                ('IoL_password', api_v1.Encrypt.EncryptedPasswordField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IoLCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('company_id', models.IntegerField(default=None)),
                ('username', models.CharField(max_length=255)),
                ('password', api_v1.Encrypt.EncryptedPasswordField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='balance',
            name='company_id',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='balance',
            name='user_id',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='buysellmovement',
            name='company_id',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='buysellmovement',
            name='user_id',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='depositextractionmovement',
            name='company_id',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='depositextractionmovement',
            name='user_id',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='holding',
            name='company_id',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='holding',
            name='user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
