# Generated by Django 4.1.4 on 2023-06-07 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0002_cocoscredentials_encryptedmodel_iolcredentials_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='company_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='balance',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='buysellmovement',
            name='company_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='buysellmovement',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cocoscredentials',
            name='company_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='depositextractionmovement',
            name='company_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='depositextractionmovement',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='holding',
            name='company_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='holding',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='iolcredentials',
            name='company_id',
            field=models.IntegerField(default=0),
        ),
    ]
