# Generated by Django 4.1.4 on 2023-06-07 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0003_alter_balance_company_id_alter_balance_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='user_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='buysellmovement',
            name='user_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='cocoscredentials',
            name='user_id',
            field=models.IntegerField(max_length=255),
        ),
        migrations.AlterField(
            model_name='depositextractionmovement',
            name='user_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='holding',
            name='user_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='iolcredentials',
            name='user_id',
            field=models.IntegerField(max_length=255),
        ),
    ]
