# Generated by Django 4.1.4 on 2023-06-07 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0004_alter_balance_user_id_alter_buysellmovement_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocoscredentials',
            name='user_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='iolcredentials',
            name='user_id',
            field=models.CharField(max_length=255),
        ),
    ]
