# Generated by Django 4.1.4 on 2023-06-07 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0005_alter_cocoscredentials_user_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=50)),
                ('logo', models.ImageField(upload_to='icons/')),
                ('about', models.TextField()),
            ],
        ),
    ]
