# Generated by Django 4.1.4 on 2023-06-16 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0007_remove_balance_company_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IoLCredentials',
            new_name='Credentials',
        ),
        migrations.DeleteModel(
            name='CocosCredentials',
        ),
    ]
