# Generated by Django 4.1.4 on 2023-06-17 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0008_rename_iolcredentials_credentials_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='logo',
        ),
        migrations.AddField(
            model_name='company',
            name='logo_url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
