# Generated by Django 4.1.4 on 2024-01-31 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0013_holding_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holding',
            name='company',
        ),
    ]
