# Generated by Django 4.1.4 on 2024-01-31 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0014_remove_holding_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='holding',
            name='company',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api_v1.company'),
        ),
    ]
