# Generated by Django 4.1.4 on 2024-01-31 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0015_holding_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='holding',
            old_name='company',
            new_name='company_id',
        ),
    ]
