# Generated by Django 4.1.4 on 2024-01-31 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0016_rename_company_holding_company_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holding',
            name='variation',
        ),
    ]
