# Generated by Django 4.1.4 on 2024-01-31 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0017_remove_holding_variation'),
    ]

    operations = [
        migrations.AddField(
            model_name='holding',
            name='variation',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
