# Generated by Django 4.1.4 on 2024-02-14 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0018_holding_variation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holding',
            name='variation',
            field=models.FloatField(null=True),
        ),
    ]
